// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArsGRcm9DZaEiOCZvsDaNUfDHhVq748uo',
    appId: '1:1081808412740:web:2a07677900a035de23dc11',
    messagingSenderId: '1081808412740',
    projectId: 'zhumush-tapp',
    authDomain: 'zhumush-tapp.firebaseapp.com',
    storageBucket: 'zhumush-tapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE4FptawswtuVg5Zs6sRw0XgPMDFbM7RI',
    appId: '1:1081808412740:android:19f396d6b7f5a7b623dc11',
    messagingSenderId: '1081808412740',
    projectId: 'zhumush-tapp',
    storageBucket: 'zhumush-tapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_bV9rWwSty380BwdiOgqSj2LIoLDMzs',
    appId: '1:1081808412740:ios:30caa033c9afa24f23dc11',
    messagingSenderId: '1081808412740',
    projectId: 'zhumush-tapp',
    storageBucket: 'zhumush-tapp.appspot.com',
    iosBundleId: 'com.maksatbek.meenet.meenet',
  );
}
